include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    avoid_unnecessary_containers: true
    avoid_print: true
    prefer_single_quotes: true
    sort_child_properties_last: true
    use_key_in_widget_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_final_fields: true
    unnecessary_const: true
    unnecessary_new: true
    avoid_function_literals_in_foreach_calls: true
    prefer_collection_literals: true
    prefer_spread_collections: true
    unnecessary_null_in_if_null_operators: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    avoid_returning_null_for_void: true
    avoid_web_libraries_in_flutter: true
    no_logic_in_create_state: true
    prefer_void_to_null: true
    sized_box_for_whitespace: true
    use_full_hex_values_for_flutter_colors: true
    prefer_relative_imports: true

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore
